-- SDKONGRE requested five-item update
begin;

update public.process_steps set title='BRIEF', subtitle='İhtiyaçların Doğru Analizi ile Sağlam Bir Başlangıç', description='Her başarılı organizasyonun temelinde doğru bir ihtiyaç analizi bulunur. Bu nedenle proje sürecine başlamadan önce kurumun beklentilerini, hedeflerini ve organizasyonun genel kapsamını detaylı şekilde değerlendiriyoruz. Gerçekleştirdiğimiz detaylı brief toplantıları sayesinde organizasyonun yol haritasını oluşturarak sonraki süreçlerin eksiksiz ilerlemesini sağlıyoruz.', content_json='{"number":"01","items":[],"groups":[],"closing":"","outputs":[]}'::jsonb, order_no=1, updated_at=now() where locale='tr' and step_key='brief';
update public.process_steps set title='PLANLAMA', subtitle='Her Detayın Önceden Tasarlandığı Profesyonel Hazırlık Süreci', description='Planlama aşaması, organizasyonun başarısını doğrudan etkileyen en kritik süreçlerden biridir. Bu aşamada tüm operasyonel ve teknik detaylar sistematik şekilde oluşturulur. Planlama sürecinde tüm paydaşlar arasında koordinasyon sağlanarak organizasyon gününe kadar gerçekleşecek her adım netleştirilir.', content_json='{"number":"02","items":[],"groups":[],"closing":"","outputs":[]}'::jsonb, order_no=2, updated_at=now() where locale='tr' and step_key='planlama';
update public.process_steps set title='TEKLİF', subtitle='Şeffaf, Anlaşılır ve İhtiyaca Özel Çözümler', description='Planlama çalışmaları tamamlandıktan sonra organizasyonun tüm kapsamını içeren detaylı teklif dosyası hazırlanır. Amacımız yalnızca maliyet sunmak değil; kurumun ihtiyaçlarına uygun, maksimum verim sağlayacak sürdürülebilir bir çözüm modeli geliştirmektir.', content_json='{"number":"03","items":[],"groups":[],"closing":"","outputs":[]}'::jsonb, order_no=3, updated_at=now() where locale='tr' and step_key='teklif';
update public.process_steps set title='ONAY', subtitle='Sürecin Netleştirildiği ve Projenin Başlatıldığı Aşama', description='Teklif değerlendirme sürecinin ardından proje detayları karşılıklı olarak gözden geçirilir ve son hali oluşturulur. Hizmet kapsamı kesinleştirilir. Operasyon ekibi oluşturulur. İş planları kesinleştirilir. İletişim ve koordinasyon süreçleri tanımlanır. Onay aşaması sayesinde tüm paydaşlar aynı hedef doğrultusunda hareket eder ve uygulama süreci kontrollü şekilde başlatılır.', content_json='{"number":"04","items":[],"groups":[],"closing":"","outputs":[]}'::jsonb, order_no=4, updated_at=now() where locale='tr' and step_key='onay';
update public.process_steps set title='OPERASYON', subtitle='Organizasyonun Sahadaki Kusursuz Yönetimi', description='Operasyon süreci, hazırlıkların gerçeğe dönüştüğü ve organizasyonun tüm detaylarının uygulandığı aşamadır. SD Kongre operasyon ekibi etkinlik öncesi, etkinlik süresince ve etkinlik sonrasında tüm süreçlerin koordinasyonunu sağlar.', content_json='{"number":"05","items":[],"groups":[],"closing":"","outputs":[]}'::jsonb, order_no=5, updated_at=now() where locale='tr' and step_key='operasyon';
update public.process_steps set title='RAPORLAMA', subtitle='Ölçülebilir Sonuçlar ve Stratejik Değerlendirme', description='Bir organizasyonun başarısı yalnızca tamamlanmış olmasıyla değil, elde edilen çıktılarla değerlendirilir. Bu nedenle proje sonunda kapsamlı raporlama ve analiz çalışmaları gerçekleştiriyoruz. Sunulan raporlar sayesinde kurumlar organizasyon yatırımlarının çıktılarını somut verilerle değerlendirebilir ve gelecekteki projelerini daha verimli planlayabilir.', content_json='{"number":"06","items":[],"groups":[],"closing":"","outputs":[]}'::jsonb, order_no=6, updated_at=now() where locale='tr' and step_key='raporlama';

commit;
